-- This migration was generated by Gemini to reflect the current state of the remote database.
-- It is based on the schema exported from the Supabase dashboard.

-- Create custom types first if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'customer_type_enum') THEN
        CREATE TYPE public.customer_type_enum AS ENUM ('business', 'individual');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'salutation_enum') THEN
        CREATE TYPE public.salutation_enum AS ENUM ('Mr.', 'Mrs.', 'Ms.', 'Miss', 'Dr.');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'currency_enum') THEN
        CREATE TYPE public.currency_enum AS ENUM ('USD', 'EUR', 'GBP', 'INR');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_terms_enum') THEN
        CREATE TYPE public.payment_terms_enum AS ENUM ('net_15', 'net_30', 'net_60', 'due_on_receipt');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'invoice_status') THEN
        CREATE TYPE public.invoice_status AS ENUM ('draft', 'sent', 'paid', 'overdue', 'cancelled');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'discount_type_enum') THEN
        CREATE TYPE public.discount_type_enum AS ENUM ('percentage', 'fixed');
    END IF;
END
$$;

-- Create tables
CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  owner uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  industry text NOT NULL,
  country text NOT NULL,
  state text NOT NULL,
  address text,
  currency text NOT NULL,
  language text NOT NULL,
  timezone text NOT NULL,
  gst boolean DEFAULT false,
  invoicing text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  address text,
  updated_at timestamp with time zone,
  theme text DEFAULT 'light'::text,
  currency text DEFAULT 'USD'::text,
  date_format text DEFAULT 'MM/DD/YYYY'::text
);

CREATE TABLE IF NOT EXISTS public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT ''::text,
  email text NOT NULL,
  created_at timestamp without time zone,
  address text,
  city text,
  country text,
  gstin bigint,
  state text,
  zip bigint,
  auth_user_id uuid,
  salutation public.salutation_enum,
  first_name text,
  last_name text,
  display_name text,
  currency public.currency_enum,
  work_phone text,
  mobile text,
  pan text,
  payment_terms public.payment_terms_enum,
  portal_language text,
  billing_attention text,
  billing_country text,
  billing_address1 text,
  billing_address2 text,
  billing_city text,
  billing_state text,
  billing_pin text,
  billing_phone text,
  billing_fax text,
  shipping_attention text,
  shipping_country text,
  shipping_address1 text,
  shipping_address2 text,
  shipping_city text,
  shipping_state text,
  shipping_pin text,
  shipping_phone text,
  shipping_fax text,
  website text,
  department text,
  designation text,
  twitter text,
  skype text,
  facebook text,
  allowlogin boolean DEFAULT false,
  customer_type public.customer_type_enum,
  company_name text
);

CREATE TABLE IF NOT EXISTS public.customer_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id uuid REFERENCES public.customers(id) ON DELETE CASCADE,
  address_line1 text NOT NULL,
  address_line2 text,
  city text NOT NULL,
  state text NOT NULL,
  postal_code text NOT NULL,
  country text NOT NULL,
  is_default_billing boolean DEFAULT false,
  is_default_shipping boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  owner uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT,
  number text UNIQUE,
  issue_date date DEFAULT CURRENT_DATE,
  due_date date,
  status public.invoice_status DEFAULT 'draft'::invoice_status,
  subtotal numeric NOT NULL DEFAULT 0,
  tax numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  payment_terms text,
  currency text NOT NULL DEFAULT 'USD'::text,
  billing_address_id uuid REFERENCES public.customer_addresses(id) ON DELETE SET NULL,
  shipping_address_id uuid REFERENCES public.customer_addresses(id) ON DELETE SET NULL,
  user_company_name text,
  authorized_signature text,
  color_theme text,
  logo_url text,
  user_address text,
  user_contact text,
  tax_amount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  tax_rate numeric NOT NULL DEFAULT 0,
  shipping_method text,
  tracking_number text,
  shipping_cost numeric DEFAULT 0,
  discount_type public.discount_type_enum,
  discount_amount numeric DEFAULT 0,
  custom_fields text,
  payment_gateway text,
  payment_gateway_order_id text,
  payment_gateway_payment_id text,
  is_recurring boolean,
  recurring_frequency text,
  recurring_start_date date,
  recurring_end_date date,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  invoice_id uuid REFERENCES public.invoices(id) ON DELETE CASCADE,
  description text,
  quantity numeric,
  unit_price numeric,
  amount numeric,
  line_total double precision,
  tax_rate numeric NOT NULL DEFAULT 0,
  discount_type public.discount_type_enum,
  discount_amount numeric DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  invoice_id uuid NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  amount numeric NOT NULL,
  payment_date date,
  method text,
  notes text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.invoice_activity (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  invoice_id uuid NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  activity_type character varying NOT NULL,
  comments text,
  created_at timestamp with time zone DEFAULT now(),
  payment_id uuid REFERENCES public.payments(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  unit_price numeric,
  tax_rate numeric,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.recurring_invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  frequency text NOT NULL,
  start_date date NOT NULL,
  end_date date,
  last_generated_date date,
  next_generation_date date,
  status text NOT NULL DEFAULT 'active'::text,
  invoice_template jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.expenses (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  category text,
  description text,
  amount numeric NOT NULL,
  expense_date date NOT NULL,
  receipt_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);
